language: cpp
matrix:
  include:
  - os: linux
git:
  submodules: false
before_install: 
before_script: 
script:
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then ninja -j1; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then mv knossos.app KNOSSOS.app; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/Cellar/qt5/${OSXQT}/bin/macdeployqt KNOSSOS.app; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then zip -r KNOSSOS.app.zip KNOSSOS.app; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then cp KNOSSOS.app.zip ../..; fi
  ## TEST
  - zip -r KNOSSOS.app.zip version

deploy:
  provider: releases
  file: KNOSSOS.app.zip
env:
  global:
    secure: a6Laxv9zjCIi2l+2/21wh2eXmd+I9fOLLSd/DbVYCKBMMZWolPlHsYqASG5oGAEr4X5OEgtoMsXRy9g3mb9qhpgGmRqcrAl+iyY4AsBpVftVSlzBvpzbfyjtT8WpoBy2IIzG0dCamaDo9nfn0W49S/YUi1g21UyKnZue0JqAC28ysJaNXywjz+LtToA8L/Ya0ej5R7bCPewOw2GmHocWJfJWl/9+I8OzxV7QgmFSYiRbw0NoHJu7nVm8eAfuBNXpH7iqvx7y4Gyz5NZ4tud2WXmidPaJMmqu0hgr+BlIO7G/spdVkXarBxml9bUBMsG20p8Bq3+EAx+88bYVW4lFc41hvkbZ6HwrC8SxINK5p7/gZt33YpfrGrRiudQ+zFvZrvsU6rYlHnC5ramePi1UBBWsXyKwkHhWFJ1mpbXU4y6kfCwsDTaFA0OsPcFWzYwKXM3gGqCW5zNIBx9bWXN3AX6EEAxsu6HTFEUmzp2wECiYhPO8q7a6UmmH2syVKbx+1RSzxvGSUFibfo6FE8jK7wg+PKtdm2/FSGlgCy7Efcb/dDKR3hrhE9b6TCgmAj9Qrfwo5SqaseLaFpGHIyR4Q6T18AQv1L6oAcJiAF2mLoAdj5ytXTBMTRC3AS477pu4isUZbm03VBBuLQmGjisJooAuWSQk8DUPMakIO4BJYo8=
