language: cpp
matrix:
  include:
  - os: linux
git:
  submodules: false
before_install: 
before_script: 
script:
- zip -r KNOSSOS.app.zip version
deploy:
  provider: releases
  file: KNOSSOS.app.zip
env:
  global:
    secure: MvFQcPpDUMhA3DXB9g+Wz8WKskddOmW2LHu5oAdoUUjehaCqGM0Qvr0mmtQ1MtALjDKY2Un4IHa4RwX/HQTzG/kQ745HZYaS9b64l+g29rYmd84US7VI8gIDHT+SXZ/BjvEclVsOvUZsXdd7a4KxHqVVb08Awstg2uV02N9561Atdm8kQKW9q/2nMhtdNiRvUhi6LdockE0Y3ElwV7ft4cSgeIcI9i3BHsBZ47psyn/8NPGOtEfe2MHoFx8Tpk7X8cc83pmz0xTHmcrk8Wffx13WvY5SKDmvV4SmTdsZB1Z2n0pXQf1cVVsqGTOdPvqnvPLODxFSh8oO7nqGeyTtwYzhQxnoYtvkhRzpIliUGWZJ2cyqmnM5k1zed0DAP52V4Ejpnrxkh2Ytqm76qvBntwQowJUjrA8NVqo/YeGQFz92R3gNqeZCNGweBhDlo7fnOcEOX8HA1HIueO7/VyMHk/M1FLdorWuFBAU0fXPVBqChwVj+JyYafSyI6ScuinCTCV7+UgpJV+ihRa88Zjzdo7LTwgbvbbqFp5WTZeKOu4CA2q3BD6a/poXHDsDO6E8rExqG53d8ckaDq6WGpL6Cth7lpW9VbqbVC218Hv00ugYbPA5fzaG5MzjxeFy/oqNxnhdFrF3bQteyGncTEZMvT1LN1vBoSxytcZmUXSSWXiQ=
