env:
  global:
    - TRAVIS_TAG=nightly

language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    services: docker
  #- os: osx
  #  osx_image: xcode8.2
git:
  submodules: false

before_install: 
  #OSX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export RELEASE_PKG_FILE=linux64.KNOSSOS.nightly.AppImage; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir artifact; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then git clone https://github.com/knossos-project/knossos.git && cd knossos; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export RELEASE_PKG_FILE=KNOSSOS.app.zip; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5 snappy quazip ninja cgal; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CXXFLAGS="-I/usr/local/opt/qt5/include"; fi #qt5.8.0 is keg-only
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then OSXQT=`ls /usr/local/Cellar/qt5/`; fi #find current version (dir) of installed qt
  
before_script: 
#OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://github.com/al3xst/PythonQt/releases/download/nightly-mac/pythonqt.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar -xvf pythonqt.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir knossos_build && cd knossos_build; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -G Ninja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH="/Users/travis/build/al3xst/knossos-nightly/knossos/pythonqt/lib/cmake/;/usr/local/Cellar/qt5/${OSXQT}/lib/cmake/;/usr/local/opt/qt5/lib/" ..; fi
 
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ninja -j1; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mv knossos.app KNOSSOS.app; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/Cellar/qt5/${OSXQT}/bin/macdeployqt KNOSSOS.app; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then find / -name "libCGAL.12.0.0.dylib"; fi
  #run macdeployqtfix
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then KPATH=`pwd`; sudo python macdeployqtfix.py /usr/local/Cellar/qt5/${OSXQT}/ ${pwd}/KNOSSOS.app; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then zip -r KNOSSOS.app.zip KNOSSOS.app; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls -al .; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cp KNOSSOS.app.zip ../..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls -al ../..; fi
  
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run -it --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /dev:/dev -v ${PWD}/artifact:/root/artifact knossosal3xst/knossos-project-arch /bin/bash -c 'cd /root/; ./build_and_pack.sh'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cp artifact/${RELEASE_PKG_FILE} .; fi
  
deploy:
  provider: releases
  api_key:
    secure: 35guXMCYs1UKXHNia+0aLITTDdCtXjclYYANUbHxyUQaIlkPf9F0HUdKM3ng0TvvFIMn9MPybKmL60QLMnzBXRjlAszKvpPWtffU0MYlXKYrgdw5SejqIFCNHE4Fm1iDEdo3Brx8WihmyzysKVeuytAxh0Z+GJ5ZiFq2TQO3xoiRd8MM0nwcdvnvgWEZnFjVibLJpeEr1zcglsHVCCSQuYeCoJdWFNeeNx49u++HMk5fYWa+ZHcmIiAMJagU0VavGeJyOw4YVI5MhFdNvszd6egZUGPr0QOMUJQiLn2AKqfLtB3oSQkk2L1m6j0ndvMFqEVY5pgBUWrP7h0rg+iIvhcnEQrD9oHZw2aYet+v3EVVzTfWmlCt81XSb+MXU7iiZFhhTczjIqcaRUVJMrIe9/qs4t3gFLKwilsx8KtOwrzVqnbyIlPuAZcbIMZM8DkMVOkrbfnWsIDR3D9Shn9oi5OFUXhOpTiSM0iY3dpCn+86DIlecU/aA6MBHVKCzFZzjXaXYnhwo0U0/xBs9ynfXjdRMPEZDZOAgLRvZIoOSDtCJPThNllMTK3isLALzSvd7aqX/MFvCYM/UdcSjrudlYrt7ArNN0TcnFZOd9PpWNieCRS+U/+lTMg2jEn0Sy1ln6GZDTqrXcoz3i9Q44rNC4WJKiQf7p/maoOzzEjBVzo=
  file_glob: true
  file: ${RELEASE_PKG_FILE}
    
  skip_cleanup: true
  overwrite: true
  on:
    repo: al3xst/knossos-nightly
    all_branches: true
