language: cpp
matrix:
  include:
  - os: linux
git:
  submodules: false
before_install: 
before_script: 
script:
- zip -r KNOSSOS.app.zip version
deploy:
  provider: releases
  api_key:
    secure: 35guXMCYs1UKXHNia+0aLITTDdCtXjclYYANUbHxyUQaIlkPf9F0HUdKM3ng0TvvFIMn9MPybKmL60QLMnzBXRjlAszKvpPWtffU0MYlXKYrgdw5SejqIFCNHE4Fm1iDEdo3Brx8WihmyzysKVeuytAxh0Z+GJ5ZiFq2TQO3xoiRd8MM0nwcdvnvgWEZnFjVibLJpeEr1zcglsHVCCSQuYeCoJdWFNeeNx49u++HMk5fYWa+ZHcmIiAMJagU0VavGeJyOw4YVI5MhFdNvszd6egZUGPr0QOMUJQiLn2AKqfLtB3oSQkk2L1m6j0ndvMFqEVY5pgBUWrP7h0rg+iIvhcnEQrD9oHZw2aYet+v3EVVzTfWmlCt81XSb+MXU7iiZFhhTczjIqcaRUVJMrIe9/qs4t3gFLKwilsx8KtOwrzVqnbyIlPuAZcbIMZM8DkMVOkrbfnWsIDR3D9Shn9oi5OFUXhOpTiSM0iY3dpCn+86DIlecU/aA6MBHVKCzFZzjXaXYnhwo0U0/xBs9ynfXjdRMPEZDZOAgLRvZIoOSDtCJPThNllMTK3isLALzSvd7aqX/MFvCYM/UdcSjrudlYrt7ArNN0TcnFZOd9PpWNieCRS+U/+lTMg2jEn0Sy1ln6GZDTqrXcoz3i9Q44rNC4WJKiQf7p/maoOzzEjBVzo=
  file: KNOSSOS.app.zip
  on:
    repo: al3xst/knossos-nightly
env:
  global:
    secure: MvFQcPpDUMhA3DXB9g+Wz8WKskddOmW2LHu5oAdoUUjehaCqGM0Qvr0mmtQ1MtALjDKY2Un4IHa4RwX/HQTzG/kQ745HZYaS9b64l+g29rYmd84US7VI8gIDHT+SXZ/BjvEclVsOvUZsXdd7a4KxHqVVb08Awstg2uV02N9561Atdm8kQKW9q/2nMhtdNiRvUhi6LdockE0Y3ElwV7ft4cSgeIcI9i3BHsBZ47psyn/8NPGOtEfe2MHoFx8Tpk7X8cc83pmz0xTHmcrk8Wffx13WvY5SKDmvV4SmTdsZB1Z2n0pXQf1cVVsqGTOdPvqnvPLODxFSh8oO7nqGeyTtwYzhQxnoYtvkhRzpIliUGWZJ2cyqmnM5k1zed0DAP52V4Ejpnrxkh2Ytqm76qvBntwQowJUjrA8NVqo/YeGQFz92R3gNqeZCNGweBhDlo7fnOcEOX8HA1HIueO7/VyMHk/M1FLdorWuFBAU0fXPVBqChwVj+JyYafSyI6ScuinCTCV7+UgpJV+ihRa88Zjzdo7LTwgbvbbqFp5WTZeKOu4CA2q3BD6a/poXHDsDO6E8rExqG53d8ckaDq6WGpL6Cth7lpW9VbqbVC218Hv00ugYbPA5fzaG5MzjxeFy/oqNxnhdFrF3bQteyGncTEZMvT1LN1vBoSxytcZmUXSSWXiQ=
